[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
